### ISSUE TITLE
Allow user to see what prescriptions are ready

### ISSUE THREAD

**Issue by ekimmichmitchell** [martypv/Drug-Dispenser#2]

**Comment by Magnalux** [comment]
Prerequisites: #6 #17

**Comment by ekimmichmitchell** [comment]
done when: the user can see a list of what is ready, which prescriptions are currently being filled, the prices, if the medication is insured, and the doctor who superscribed it

**Comment by groth12** [comment]
Worked for about an hour on this, stuck on an error.
