### ISSUE TITLE
Pharmacists can create orders

### ISSUE THREAD

**Issue by ben145** [martypv/Drug-Dispenser#3]

**Comment by MOOOoooD** [comment]
Done - Create valid order

**Comment by martypv** [comment]
Only took about 20 minutes

**Comment by martypv** [comment]
Took about 35 minutes

**Comment by martypv** [comment]
Added getters, setters and toString to Order class. Added create order method to Pharmacist class.

**Comment by martypv** [comment]
Also some tests
