### ISSUE TITLE
Allow pharmacist/assistant to create new user accounts

### ISSUE THREAD

**Issue by bkeith20** [martypv/Drug-Dispenser#4]

**Comment by bkeith20** [comment]
User has to present identification
Pharmacist/assistant starts account and enters information
user enters user name and password
pharmacist/assistant finalizes account

**Comment by bkeith20** [comment]
Done when can create new user account with: user name, password, and basic user information such as name, age, primary physician...

**Comment by Magnalux** [comment]
Took around two hours: might want to make sure the SQL commands are correct
