### ISSUE TITLE
Add sprint 3's new functionality to interface

### ISSUE THREAD

**Issue by Magnalux** [martypv/Drug-Dispenser#70]

**Comment by danny97101** [comment]
clients can return an order. it puts the price into their balance.

**Comment by wennbergsmithe** [comment]
need to add switch to easy open caps functionality to IF

**Comment by martypv** [comment]
needs to prompt user to set the next refill date after an order is picked up from PPM

**Comment by Magnalux** [comment]
took only 1 hour so far: includes all new functionality except easy open caps since branch is not yet merged
