### ISSUE TITLE
The system can handle the user exceeding login attempts

### ISSUE THREAD

**Issue by ekimmichmitchell** [martypv/Drug-Dispenser#8]

**Comment by Magnalux** [comment]
Prerequisites: #6 #17

**Comment by ekimmichmitchell** [comment]
done when: 
the user exceeds the number of login attempts and the account is blocked until the pharmacist can verify the user and their account.

**Comment by danny97101** [comment]
max 3 attempts -> frozen until employee unfreezes

**Comment by danny97101** [comment]
1 hour
