### ISSUE TITLE
Pharmacy Assistant can load orders to PPM

### ISSUE THREAD

**Issue by MOOOoooD** [martypv/Drug-Dispenser#9]
PA - enters login
PA - enters pwd
PA has to have access level to add orders and has access to PPM DB
PA has to validate, sign off on orders put in machine

**Comment by MOOOoooD** [comment]
Done when: Orders are loaded into PPM with PA signature

**Comment by groth12** [comment]
Worked on this, stuck on an error

**Comment by groth12** [comment]
Finished, took about an hour more.
